version: "3.8"

services:
  nextjs:
    container_name: nextjs-app-dirrochaCMS
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3096:3000"
    restart: always
    # env_file:
    #   - .env
    volumes:
      - ./:/app
      - /app/node_modules
